//! Safe builder for `pappl_pr_driver_data_t`.
//!
//! Wraps the ~85-field C struct in a chainable builder so callers don't
//! have to touch raw `pappl_sys` types directly. Simple fields are
//! generated by [`pappl_builder!`]; complex fields (media arrays, dither
//! matrices, callbacks) have hand-written methods.

use std::ffi::{c_int, CStr};

use pappl_sys::*;

use crate::macros::pappl_builder;

pappl_builder! {
    /// Chainable builder for `pappl_pr_driver_data_t`.
    ///
    /// ```ignore
    /// DriverDataBuilder::new()
    ///     .make_and_model(b"Supvan T50 Pro")
    ///     .format(c"application/vnd.cups-raster")
    ///     .resolution(203)
    ///     .monochrome()
    ///     .label_printer()
    ///     .darkness(50, 16)
    ///     .build(&mut data);
    /// ```
    pub struct DriverDataBuilder => pappl_pr_driver_data_s {
        buf    make_and_model: &'a [u8],
        c_str  format: &'static CStr,
        scalar ppm: c_int,
        scalar ppm_color: c_int,
        bool_  has_supplies: bool,
        bool_  input_face_up: bool,
        bool_  output_face_up: bool,

        scalar orient_default: u32,
        scalar quality_default: u32,
        scalar content_default: u32,
        scalar scaling_default: u32,

        scalar raster_types: u32,
        scalar force_raster_type: u32,
        scalar color_supported: u32,
        scalar color_default: u32,

        scalar duplex: u32,
        scalar sides_supported: u32,
        scalar sides_default: u32,
        scalar finishings: u32,

        bool_  borderless: bool,
        scalar left_right: c_int,
        scalar bottom_top: c_int,

        scalar kind: u32,
        scalar mode_configured: u32,
        scalar mode_supported: u32,
        scalar tear_offset_configured: c_int,

        scalar speed_default: c_int,
        scalar darkness_default: c_int,
        scalar darkness_configured: c_int,
        scalar darkness_supported: c_int,

        scalar num_bin: c_int,
        scalar bin_default: c_int,
    }
    extras {
        res: Option<(c_int, c_int)> = None,
        speed_range: Option<[c_int; 2]> = None,
        media_ptrs: Option<Vec<*const std::ffi::c_char>> = None,
        media_sizes: Option<Vec<[c_int; 2]>> = None,
        bayer4: Option<[[u8; 4]; 4]> = None,
        raster_cbs: Option<RasterCallbacks> = None,
    }
}

#[derive(Clone, Copy)]
pub(crate) struct RasterCallbacks {
    pub startjob: pappl_pr_rstartjob_cb_t,
    pub startpage: pappl_pr_rstartpage_cb_t,
    pub writeline: pappl_pr_rwriteline_cb_t,
    pub endpage: pappl_pr_rendpage_cb_t,
    pub endjob: pappl_pr_rendjob_cb_t,
    pub status: pappl_pr_status_cb_t,
}

impl<'a> DriverDataBuilder<'a> {
    /// Set resolution to a single DPI value (square pixels).
    pub fn resolution(self, dpi: c_int) -> Self {
        self.resolution_xy(dpi, dpi)
    }

    /// Set resolution with separate x and y DPI.
    pub fn resolution_xy(mut self, dpi_x: c_int, dpi_y: c_int) -> Self {
        self.res = Some((dpi_x, dpi_y));
        self
    }

    /// Shorthand: monochrome 1-bit black raster, one-sided.
    pub fn monochrome(self) -> Self {
        self.raster_types(pappl_raster_type_e_PAPPL_PWG_RASTER_TYPE_BLACK_1)
            .color_supported(pappl_color_mode_e_PAPPL_COLOR_MODE_MONOCHROME)
            .color_default(pappl_color_mode_e_PAPPL_COLOR_MODE_MONOCHROME)
            .sides_supported(pappl_sides_e_PAPPL_SIDES_ONE_SIDED)
            .sides_default(pappl_sides_e_PAPPL_SIDES_ONE_SIDED)
    }

    /// Shorthand: borderless label printer with supplies, tear-off mode.
    pub fn label_printer(self) -> Self {
        self.kind(pappl_kind_e_PAPPL_KIND_LABEL)
            .borderless(true)
            .has_supplies(true)
            .left_right(0)
            .bottom_top(0)
            .mode_configured(pappl_label_mode_e_PAPPL_LABEL_MODE_TEAR_OFF as _)
            .mode_supported(pappl_label_mode_e_PAPPL_LABEL_MODE_TEAR_OFF as _)
    }

    /// Set darkness configured value + number of supported levels.
    pub fn darkness(self, configured: c_int, levels: c_int) -> Self {
        self.darkness_configured(configured)
            .darkness_supported(levels)
    }

    /// Set speed range and default.
    pub fn speed(mut self, default: c_int, range: [c_int; 2]) -> Self {
        self.speed_range = Some(range);
        self.speed_default(default)
    }

    /// Set media from parallel name/size slices. Sets source to
    /// `"main-roll"`, type to `"labels"`, and fills `media_default` +
    /// `media_ready[0]` from the first entry.
    pub fn media(mut self, names: &[impl AsRef<CStr>], sizes: &[[c_int; 2]]) -> Self {
        self.media_ptrs = Some(names.iter().map(|n| n.as_ref().as_ptr()).collect());
        self.media_sizes = Some(sizes.to_vec());
        self
    }

    /// Tile a 4x4 Bayer dither matrix to fill both `gdither` and `pdither`.
    pub fn dither_bayer4(mut self, bayer4: &[[u8; 4]; 4]) -> Self {
        self.bayer4 = Some(*bayer4);
        self
    }

    /// Set the 5 raster callbacks + status callback.
    pub fn raster_callbacks(
        mut self,
        startjob: pappl_pr_rstartjob_cb_t,
        startpage: pappl_pr_rstartpage_cb_t,
        writeline: pappl_pr_rwriteline_cb_t,
        endpage: pappl_pr_rendpage_cb_t,
        endjob: pappl_pr_rendjob_cb_t,
        status: pappl_pr_status_cb_t,
    ) -> Self {
        self.raster_cbs = Some(RasterCallbacks {
            startjob,
            startpage,
            writeline,
            endpage,
            endjob,
            status,
        });
        self
    }

    /// Write all configured values into `target`.
    ///
    /// # Safety
    /// `target` must be a valid, mutable `pappl_pr_driver_data_t`.
    /// Any C-string pointers (media names, format) must outlive the struct.
    pub unsafe fn build(self, target: &mut pappl_pr_driver_data_s) {
        self.apply_simple(target);

        if let Some((dx, dy)) = self.res {
            target.num_resolution = 1;
            target.x_resolution[0] = dx;
            target.y_resolution[0] = dy;
            target.x_default = dx;
            target.y_default = dy;
        }

        if let Some(range) = self.speed_range {
            target.speed_supported = range;
        }

        if let Some(ref ptrs) = self.media_ptrs {
            let sizes = self.media_sizes.as_deref().unwrap_or(&[]);
            let n = ptrs.len().min(256);
            target.num_media = n as c_int;
            for (i, &p) in ptrs.iter().enumerate().take(n) {
                target.media[i] = p;
            }

            if n > 0 && !sizes.is_empty() {
                crate::util::copy_to_c_buf(
                    &mut target.media_default.size_name,
                    CStr::from_ptr(ptrs[0]).to_bytes(),
                );
                target.media_default.size_width = sizes[0][0];
                target.media_default.size_length = sizes[0][1];
                target.media_default.left_margin = 0;
                target.media_default.right_margin = 0;
                target.media_default.top_margin = 0;
                target.media_default.bottom_margin = 0;
                crate::util::copy_to_c_buf(&mut target.media_default.source, b"main-roll");
                crate::util::copy_to_c_buf(&mut target.media_default.type_, b"labels");
                target.media_ready[0] = target.media_default;
            }

            target.num_source = 1;
            target.source[0] = c"main-roll".as_ptr();
            target.num_type = 1;
            target.type_[0] = c"labels".as_ptr();
        }

        if let Some(bayer) = self.bayer4 {
            for r in 0..16 {
                for c in 0..16 {
                    target.gdither[r][c] = bayer[r % 4][c % 4];
                }
            }
            target.pdither = target.gdither;
        }

        if let Some(cbs) = self.raster_cbs {
            target.rstartjob_cb = cbs.startjob;
            target.rstartpage_cb = cbs.startpage;
            target.rwriteline_cb = cbs.writeline;
            target.rendpage_cb = cbs.endpage;
            target.rendjob_cb = cbs.endjob;
            target.status_cb = cbs.status;
        }
    }
}
